name: pipeline SAST-SCA-DAST-SCANCONTAINER
on:
  push:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest
    name: Scan code quality-sast
    steps:
      - uses: actions/checkout@v3
      - name: setup-jdk
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        run: ./gradlew build jacocoTestReport sonarqube --info
        env:
                # Needed to get some information about the pull request, if any
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    

          
  sca:
      name: Scan SCA with SNYK
      needs: sast
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Run SNYK for check vulnerabilities
          uses: snyk/actions/gradle-jdk11@master
          continue-on-error: true
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}   
  push_to_registry:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      needs: sca
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: maupuert/api-demo-te
        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }} 
  scan-dockerfile:
      runs-on: ubuntu-latest
      needs: push_to_registry
      steps:
        - name: Run Snyk to check Docker image for vulnerabilities
          uses: snyk/actions/docker@master
          continue-on-error: true
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: maupuert/api-demo-te                      